spring.application.name=ecommerce
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=deepali_kokate
spring.datasource.password=Deepali123$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
server.port=8100